### ISSUE TITLE
Secrets Provider support Rotations and deployed separately - Research

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/secrets-provider-for-k8s#102]
### Overview
We would like to improve the secret provider scope and support
Milestone 1
- Secrets Provider runs and deployed without affecting the app deployment or app life cycle
- Secrets Provider can serve many apps
Milestone 2
- Secrets Provider support rotations 

#### Milestone 1
**As a** operation team, Liz
**I would like to** deploy Secret provider in a way that do not interfere with my application deployment
**So That** my app can be upgraded and managed in separation from secret provider

**AS an** k8s app developer, David
**I would like to** fetch my secret in an easy and naive way without changing my code
**So That** my app will get the most updated secret as a K8s secret (usually provided in the deployment as an env var or file).
The secrets are expected to be provided in advance before the app is initialised.

If the secrets change value please look at :How to handle rotation? section below

#### Milestone 2
**AS an** k8s app developer, David
**I would like to** fetch my secret in an easy and naive way without changing my code
**So That** my app will get the most updated secret as a K8s secret (usually provided in the deployment as an env var or file).
The secrets are expected to be provided in advance before the app is initialized.

**If the secrets change value please look at :How to handle rotation? section below**

**As an** info sec can be Vault admin or Conjur admin or DAP admin
**I would like to** rotate the secret value in Vault or in DAP manually or using CPM policies
**So That** I'll stay secure and follow security best practices

**As an** info sec can be Vault admin or Conjur admin or DAP admin
**I would like to** change the secret value 
**So That** I'll stay secure and follow security best practices

### Requirements for  Milestone 1
In this phase Secrets provider needs to be able to run as a separate entity and serve multiple application containers that runs on multiple pods.

### Deployment requirements 

- Secrets provider needs to be able to run as a separate entity and serve multiple application containers that runs on multiple pods.
- The lifecycle of this deployment option should support also upgrade and removal of deployment
- Provide a way for our customer to understand the state of the secret provider - when it finished initializing 
- The deployment method of the secret provider should be native to K8s. Deployment and uninstall should be done using **helm**

**Deployment Flow with helm chart**
Prerequisite
 1. Configure K8s Secrets with conjur-map metadata defined 
     Optional: add label to K8s Secret (Milestone 2)

2. Create custom-values.yaml file that will optionally contain the following params:

 2.1 Service Account Name (default: secret-provider-account)
 2.2 Role Name(default: secret-provider-role)
 2.3 Role Binding Name(default: secret-provider-role-binding)
 2.4 Follower Connection Timeout (default: 10 seconds) may stay internal ??
 2.5 Retries count (default: 2) secret provider will wait "Follower Connection Timeout" amount of time to authenticate + get secrets from the follower, and if timeout is reached and we will retry according to "Retries count".
 2.6 Sync Interval Time (default: 5 minutes) (Milestone 2) 
 2.7 If label filtering is defined: K8s Secret Label parameter should be added to custom-values.yaml (Milestone 2)
When the parameter does not appear in file - default value for it is used
 2.8 Rotation support - Enabled/ Disabled (Milestone 2) 

3. Install helm chart for secret provider (helm chart should create service Account, Role / ClusterRole and RoleBinding / ClusterRoleBinding, as well as Job/Deployment that will run)
Installation will print a message including data about deployment mode (if it is Job or Deployment)

### How to handle rotation?
It is the secret provider responsibility to update the K8s secret after rotation yet it is the application developer responsibility to make sure the application is reading the updated value.

### Configuration requirements

- The Secrets Provider needs to support rotation and update secrets once changed one way to do it is based on a time interval. 
- The time interval should be configurable using a config named "SECRETS_UPDATE_INTERVAL" and with a default that is every 5 minutes (to match the Synchronizer defaults). Ideally, this number should be as small as possible. 
- Having a recommendation for a minimum time interval is important. 
- The configuration should be in seconds and it should have a minimum recommendation.
-  The ability to support rotation should be configurable as well

### Performance requirements
Please test and document how many secrets can be updated in 5 minutes in average where a secret should be either extreme long password or one vault account which is 5 vars username address port password dns
Have a test that make sure we are meeting this SLA once it is determined 
Number of secret providers per follower is expected to be 1000.

###Requirements for both Milestones
### Logs & Supportability - 

- Make sure each interval is written down and it is easy to see what had happen in each interval
- Monitoring
**- We need to provide a way to understand the status of the Secret provider (health)**
- Supportability can be tricky here as we now serve many applications please document as much as possible information that can help in supportability.
Usually the status of pod / container in K&S is provided by probes together with kubectl / oc commands. 

### Audit

- If in the init container solution we have authenticated ourselves as the application (sitting in the same pod) now we are serving more apps and pods. The audit would be hard to read. Think about this and see if A. There is a problem B. How may we solve it.

### Innovative

- If possible please write a patent about this (smile)
- If not one can suggest new ways to authenticate in k8s in new ways. One can think of other ways to integrate with K8s Secrets 

Test Env
Please test with followers inside and outside (deployed on VM with LB in front of it) the cluster.  

**DOD**
- [x] The process logic of this feature should be written by PO and tech lead hand by hand 
- [x] Research page with all info regarding Secrets Provider support Rotations and deployed separately
- [x] Test plan written and reviewed by PO & QAA
- [x] Security review was done and issues were raised
- [x] Research results presented and shared
- [x] High level effort estimations and risks

**Comment by orenbm** [comment]
We should also update the [DockerHub page](https://hub.docker.com/r/cyberark/secrets-provider-for-k8s) as part of this effort

**Comment by InbalZilberman** [comment]
More helm configurations that will be provided in the custom_values.yml
2.9 SECRET_DESTINATION (default: k8s_secrets)
2.10 All other configurations that are needed for the current secret provider to work like: K8S_SECRETS, CONJUR_AUTHN_URL ....

**Comment by sigalsax** [comment]
Solution doc can be found here: https://github.com/cyberark/secrets-provider-for-k8s/pull/151
