### ISSUE TITLE
Secrets Provider support multiple apps

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/secrets-provider-for-k8s#163]
### Overview
We would like to improve the secret provider scope and support
**Milestone 1**

Secrets Provider runs and deployed without affecting the app deployment or app life cycle
Secrets Provider can serve many apps
**Milestone 2**
Secrets Provider support rotations
 In this Epic we will concentrate in **Milestone 1** implementation phase
Use cases

**As a** operation team, Liz
**I would like to** deploy Secret provider in a way that do not interfere with my application deployment
**So That** my app can be upgraded and managed in separation from secret provider

**AS an** k8s app developer, David
**I would like to** fetch my secret in an easy and naive way without changing my code
**So That** my app will get the most updated secret as a K8s secret (usually provided in the deployment as an env var or file).
The secrets are expected to be provided in advance before the app is initialised.
### Requirements for  Milestone 1
In this phase Secrets provider needs to be able to run as a separate entity and serve multiple application containers that runs on multiple pods.

### Deployment requirements 

- Secrets provider needs to be able to run as a separate entity and serve multiple application containers that runs on multiple pods.
- The lifecycle of this deployment option should support also upgrade and removal of deployment
- Provide a way for our customer to understand the state of the secret provider - when it finished initializing 
- The deployment method of the secret provider should be native to K8s. Deployment and uninstall should be done using **helm**

**Deployment Flow with helm chart**
Prerequisite
 1. Configure K8s Secrets with conjur-map metadata defined 
     Optional: add label to K8s Secret (Milestone 2)

2. Create custom-values.yaml file that will optionally contain the following params:

 2.1 Service Account Name (default: secret-provider-account)
 2.2 Role Name(default: secret-provider-role)
 2.3 Role Binding Name(default: secret-provider-role-binding)
 2.4 Follower Connection Timeout (default: 10 seconds) may stay internal ??
 2.5 Retries count (default: 2) secret provider will wait "Follower Connection Timeout" amount of time to authenticate + get secrets from the follower, and if timeout is reached and we will retry according to "Retries count".
 2.6 Sync Interval Time (default: 5 minutes) (Milestone 2) 
 2.7 If label filtering is defined: K8s Secret Label parameter should be added to custom-values.yaml (Milestone 2)
When the parameter does not appear in file - default value for it is used
 2.8 Rotation support - Enabled/ Disabled (Milestone 2) 

3. Install helm chart for secret provider (helm chart should create service Account, Role / ClusterRole and RoleBinding / ClusterRoleBinding, as well as Job/Deployment that will run)
Installation will print a message including data about deployment mode (if it is Job or Deployment)
### Performance requirements
Please test and document how many secrets can be updated in 5 minutes in average where a secret should be either extreme long password or one vault account which is 5 vars username address port password dns
Have a test that make sure we are meeting this SLA once it is determined 
Number of secret providers per follower is expected to be 1000.

###Requirements for both Milestones
### Logs & Supportability - 

- Make sure each interval is written down and it is easy to see what had happen in each interval
- Monitoring
**- We need to provide a way to understand the status of the Secret provider (health)**
- Supportability can be tricky here as we now serve many applications please document as much as possible information that can help in supportability.
Usually the status of pod / container in K&S is provided by probes together with kubectl / oc commands. 

### Audit

- Make sure audits are written right in Conjur/DAP

h2. DOD
- [ ] Implement Secrets Provider support multiple apps
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [ ] UT written for all classes\functions\major logic flows and passed successfully
- [ ] Security action items were taken
- [ ] Supportability tasks were written - link if something changed
 - [ ] Enhance logs and supportability according to [https://ca-il-confluence.il.cyber-ark.com/display/rndp/Okta+Integration+With+Conjur+-+CLI#OktaIntegrationWithConjur-CLI-LogsGuidelines]
- [ ] Fill in the logs and place here a link to the logs files - link if something changed
- [ ] Logs were reviewed by TW and PO
- [ ] Fill in the configurations in feature doc
- [ ] Are there new Audits to this feature? If so please document them and provide here a link
- [ ] Configurations were reviewed by PO - link if something changed
-[ ] Fill in Messages and Code Page  https://ca-il-confluence.il.cyber-ark.com/display/rndp/Conjur+error+messages+and+responses#/
- [ ] Documentation HO to TW and review docs

**Comment by sigalsax** [comment]
I want to clarify a couple of things

> 2.5 Retries count (default: 2) secret provider will wait "Follower Connection Timeout" amount of time to authenticate + get secrets from the follower, and if timeout is reached and we will retry according to "Retries count".
2.6 Sync Interval Time (default: 5 minutes) (Milestone 2) 

@ofira mentioned defaults for both should be 3 (Sync time 3 minutes), Retry 3 times. Are we okay with this?

The retry mechanism is if something in the process the Secrets Provider failed. When you say "secret provider will wait "Follower Connection Timeout" amount of time to authenticate + get secrets from the follower" do you mean that in between runs we will wait the SYNC_INTERVAL amount of time?
