### ISSUE TITLE
Improve secrets provider automation

### ISSUE THREAD

**Issue by eladkug** [cyberark/secrets-provider-for-k8s#259]
We want to improve our automation in several manners to make it faster / easier and better.
Its important to do such tasks while our automation is stable, so our changes can be in parallel to our coding.

DOD by priority:

 - [ ] Change our automation to work with BDD instead of bash
 - [ ] Reduce the time of the automation (Do we want to run each test in clean environment as today? )
 - [ ] Add the ability to run all the tests even if one of the tests failed
 - [ ] Add missing tests which relevant to logs (Can be unit test as well)
 - [ ] Work with CII Best Practices to understand our (will allow us to improve ourselves)
