### ISSUE TITLE
Secret provider support ocp

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/secrets-provider-for-k8s#265]
## Add and remove support of OCP

- [ ] Remove support of OCP 3.9 and 3.10 in tests and read me

- [ ] Add support of OCP 4.5 tests and read me or create a page with delivery plan (depend on the EE)

- [ ] Make sure Secret provider system requirements are part of docs like: 
  - [ ] https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/scl_SystemReq.htm
  - [ ] https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Integrations/k8s-ocp/cjr-secrets-provider-lp.htm#Systemrequirements

- Note that these requirements are hard to find in our documentation, they are scattered in too many places. We should have a solid reference with full coverage from the main [system requirements](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Deployment/platforms/dap-sysreqs-server.htm?tocpath=Setup%7CDAP%20Requirements%7CDAP%20System%20Requirements%7C_____1) section

**Comment by orenbm** [comment]
@InbalZilberman i left one requirement unticked because i don't think that we need to update the secretless docs after this change. Can you please update the description?

**Comment by InbalZilberman** [comment]
@orenbm from not long ago there is a new system requirement chapter in SP docs that also specify the OCP support we have. hence this need to be updated - but this is part of the doc issue you opened and we agreed the epic can be closed even if the doc is not.
